import type { Metadata } from "next";
import { Comforter } from "next/font/google";
import "./globals.css";

const comforter = Comforter({
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comforter.className} text-3xl antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
